// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvjifdniizjhcynapyjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2amlmZG5paXpqaGN5bmFweWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzQ3MTAsImV4cCI6MjA3Mzg1MDcxMH0.PkU2Hm-yXNbDRc3Xu1vYS5tPSSLOuOj52rWV2Q8rkzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});